### ISSUE TITLE
Respect options.host not only options.hostname

### ISSUE THREAD

**Issue by wcho** [gajus/global-agent#10]
It seems that `global-agent` only respects `options.hostname`. But node.js reference says that `options.hostname` is an alias of `options.host`.
https://nodejs.org/docs/latest-v10.x/api/http.html#http_http_request_options_callback
Proxy is not used in the following code. 
```
const http = require('http');
require('global-agent/bootstrap');
global.GLOBAL_AGENT.HTTP_PROXY = 'http://127.0.0.1:8080';
const options = {
  host: 'some.host.com'
};
http.get(options, res => {
  console.log(res.statusCode, res.headers);
});
```

**Comment by gajus** [comment]
Sounds like a simple first contribution. Are you available to raise a PR?

**Comment by gajus** [comment]
@wcho Can you please add a failing test case?

I cannot replicate the issue.

```js
test('proxies HTTP request (using http.get(host))', async (t) => {
  bootstrap({});

  const proxyServer = await createProxyServer();

  global.GLOBAL_AGENT.HTTP_PROXY = proxyServer.url;

  const response = await new Promise((resolve) => {
    http.get({
      host: '127.0.0.1'
    }, createHttpResponseResolver(resolve));
  });

  t.assert(response.body === 'OK');
});

```

The above works as expected.

**Comment by gajus** [comment]
Never mind. Thank you.

**Comment by wcho** [comment]
Thanks.
The test does not actually check proxied request working. It would be better to actually request proxy and http server and check the response using `beforeSendResponse`.

**Comment by gajus** [comment]
> The test does not actually check proxied request working. It would be better to actually request proxy and http server and check the response using beforeSendResponse.

Can you please add a PR?
