### ISSUE TITLE
Fails with Axios & request if used with HTTP_PROXY

### ISSUE THREAD

**Issue by pimterry** [gajus/global-agent#12]
My application needs to work in an environment with HTTP_PROXY set, and I  need to be able to proxy traffic from Axios, and from raw node.js HTTP.

Unfortunately, it seems that global-agent current breaks in this case: when proxying, libraries that do support HTTP proxies end up sending requests like `CONNECT http://proxy-address:8000https://target-address:443`, instead of the expected `CONNECT https://target-address:443`.

I've seen [your comment](https://github.com/gajus/global-agent/issues/6#issuecomment-491754798) with a little background about this, which makes sense, but doesn't solve cases like mine (which I think are fairly common - in any environment using a proxy globally, you'll normally have these variables defined).

Do you have any ideas about how to resolve this? I'd like to do so without wiping out the HTTP_PROXY variables if possible, since I'd still like those to be inherited correctly by subprocesses etc.

Notably global-tunnel-ng does successfully handle this, for both Axios & request, so it's clearly possible, but I'm not exactly sure why quite yet.

**Comment by pimterry** [comment]
Found it: https://github.com/np-maintain/global-tunnel/blob/master/index.js#L113-L117

Basically global-tunnel just deletes the environment variables itself. I can see why that works, but that's exactly what I'm trying to avoid.

One idea: how about we detect when this is happening, and avoid proxying the request in just that case? I think you can tell that a request is already being proxied from within [addRequest in Agent.js](https://github.com/gajus/global-agent/blob/master/src/classes/Agent.js#L49), by checking if:

* The `configuration` port & hostname are already set to the proxy's port & hostname
* The `request` path is actually an absolute URL, and isn't the same as the proxy's port & hostname

If both of those are true, then the request is already being proxied through the same proxy we're already using, and we can skip proxying it completely.

Does that make sense? I haven't tested it, but something like that should fix this for the general case (axios & request & anything else too), and would also let global-agent use the HTTP_PROXY/HTTPS_PROXY env vars with no risks, which would simplify things nicely.

**Comment by gajus** [comment]
> One idea: how about we detect when this is happening, and avoid proxying the request in just that case? I think you can tell that a request is already being proxied from within addRequest in Agent.js, by checking if [..]

It is worth a shot. However, I would rather have it in a way that `global-agent` overrides whatever Axios/ request are using.

**Comment by pimterry** [comment]
> I would rather have it in a way that global-agent overrides whatever Axios/ request are using.

I'd prefer to go that route to, but sadly I don't think that's possible for the general case (although it might be for some specific clients).

Any HTTP client that is intentionally proxying might do so by sending a CONNECT request to the proxy to start a tunnel, followed by tunnelling the real request down the resulting socket. I think in that case we'll only see the first request, which won't even include the real HTTP verb or headers of the request, so we won't be able to extract the 'raw' request at all. You could maybe intercept the raw socket data and parse the whole request back out from that, but it'll get very very complicated very quickly.

**Comment by pimterry** [comment]
Fixed in https://github.com/gajus/global-agent/commit/9a8e0d8433ce298247a7087708ac2895b4a506bd
