### ISSUE TITLE
How I can use proxy authentication

### ISSUE THREAD

**Issue by vedmant** [gajus/global-agent#18]
How I can use proxy authentication? I can't find anything in documentation about this.

**Comment by gajus** [comment]
```bash
$ export GLOBAL_AGENT_HTTP_PROXY=http://username:password@127.0.0.1:8080

```

**Comment by vedmant** [comment]
@gajus Thanks, still it's not that obvious, other packages have params like `proxyAuth: 'userId:password', // optional authentication`.

**Comment by roccomuso** [comment]
this should be added to the doc
