### ISSUE TITLE
Unanticipated logging

### ISSUE THREAD

**Issue by rarkins** [gajus/global-agent#19]
global-agent is part of [renovate](https://github.com/renovatebot/renovate) and then renovate is required as part of another project I have, that runs within Docker. Somehow the logs are full of global-agent logs, e.g.

```
server_1  | {"context":{"program":"global-agent","namespace":"Agent","logLevel":10,"destination":"https://index.docker.io/v2/"},"message":"not proxying request; GLOBAL_AGENT.HTTP_PROXY is not configured","sequence":39,"time":1565889150617,"version":"1.0.0"}
```

I definitely haven't set `ROARR_LOG=true` and I even tried setting `ROARR_LOG=false` but that also didn't disable them. Any idea how this can be turned off? Seems like a bug though, unless I'm mistaken.

FYI my tool uses `bunyan` for its logs, not sure if that has anything to do with it.

**Comment by rarkins** [comment]
It seems that if I set `global.ROARR = {};` before global-agent is required then it succeeds in disabling it

**Comment by rarkins** [comment]
@gajus what I describe above is just a workaround

**Comment by rarkins** [comment]
BTW, the only occurrences of `ROARR_LOG` I can find in the `roarr` repo are in the README. i.e. I can't see how it functions to turn on/off

**Comment by gajus** [comment]
@rarkins Sorry – I forgot to add `process.env.ROARR_LOG` check in the latest Roarr update. We have all logs enabled by default, so this went unnoticed. The latest release should fix it.
