### ISSUE TITLE
Aborts with TypeError on socket.setTimeout

### ISSUE THREAD

**Issue by cjk** [gajus/global-agent#20]
Just started using global-agent and it works as expected with my local proxy if I only do a small amount of request.
But as soon as the program does more requests (say > 20), it runs into a typeerror every time:
```
C:\Users\cklingb\home\proj\iparts-db-builder\node_modules\global-agent\dist\classes\Agent.js:96
      socket.setTimeout(this.socketConnectionTimeout, () => {
             ^
TypeError: Cannot read property 'setTimeout' of undefined
  at C:\Users\cklingb\home\proj\iparts-db-builder\node_modules\←[4mglobal-agent←[24m\dist\classes\Agent.js:96:14
  at Socket.<anonymous> (C:\Users\cklingb\home\proj\iparts-db-builder\node_modules\←[4mglobal-agent←[24m\dist\classes\HttpsProxyAgent.js:28:7)
  at Socket.emit (events.js:210:5)
  at emitErrorNT (internal/streams/destroy.js:91:8)
  at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I don't know what I'm doing wrong, since all works fine when doing just a few connections / working without any proxy.
Just guessing: Could it be related to #2 ?

**Comment by gajus** [comment]
Unlikely related to #2. I am using global-agent to make 100+ concurrent requests.

None the less will try to replicate.

**Comment by cjk** [comment]
@gajus Thanks, BTW I'm using `got` for making request.

**Comment by cjk** [comment]
> Unlikely related to #2. I am using global-agent to make 100+ concurrent requests.

In my case it might be even more. How can I find out where the limit is (like e.g. `max open sockets`)?
Perhaps the error is triggered if this limit is reached?

**Comment by gajus** [comment]
Never managed to replicate this issue.

**Comment by gajus** [comment]
> How can I find out where the limit is (like e.g. max open sockets)?

This would be specific to your OS, not Node.js, as far as I know.

**Comment by cjk** [comment]
Well that is too bad. I've moved to the `proxying-agent` package meanwhile and it worked flawless out of the box even under heavy load. In case someone else has similar issues.
Thanks for trying though!
