### ISSUE TITLE
Support to HTTP2

### ISSUE THREAD

**Issue by DavidBernal** [gajus/global-agent#22]
Hi, have you planned add support to HTTP2?

**Comment by gajus** [comment]
I am not familiar with what that would entail. Please do contribute though.

**Comment by viceice** [comment]
We have now this issue. We would like to enable http2 with got at https://github.com/renovatebot/renovate.

but we are stuck because of this bug. A simple reproducable is here: https://github.com/viceice/global-agent-test

**Comment by JamieMagee** [comment]
It should be possible to use the [HTTP/2 compatability API](https://nodejs.org/api/http2.html#http2_compatibility_api) to support both HTTP/1.1 and HTTP/2 simultaneously.
