### ISSUE TITLE
cannot send client certificate to the endpoint while using the proxy

### ISSUE THREAD

**Issue by ballinette** [gajus/global-agent#25]
Hi.

We have an nodejs application that need to authenticate to an API endpoint with a SSL client certificate.
For that need, we inject tls.connect() options such as `key` and `cert` to the request options, as documented here : https://nodejs.org/docs/latest-v12.x/api/https.html#https_https_request_url_options_callback

It works like expected without proxy, but while using a proxy with global-agent lib, these options are not propagated to the final request.

We should add these attributes within `createConnection` method here to fix that: https://github.com/gajus/global-agent/blob/master/src/classes/HttpsProxyAgent.js#L31

**Comment by gajus** [comment]
Cannot find where the original comment thread is, but removing `{rejectUnauthorized: false}` breaks all HTTPS proxy requests if custom ca certificate is not provided. Since this is not what most people would want, I've reverted the previous settings.

**Comment by ballinette** [comment]
Hi again
Thanks for the merge and the later fixes.

But it seems to be another issue wirh the `rejectUnauthorized` option : if the env var is unset or is set to `true` (which both mean we want to reject the request if  the server certificate is invalid, self-signed or has expired), the request is not rejected.
I don't know why yet, as according to nodejs doc, the option should be true by default if not provided...
but to make sure that we do have the expected behaviour, we should force the option to `true` by default, and to `false` if the env var is set to 0, as you did.

I'm writing another PR to fix that.

**Comment by ballinette** [comment]
=> https://github.com/gajus/global-agent/pull/27
