### ISSUE TITLE
use proxy programmatically

### ISSUE THREAD

**Issue by roccomuso** [gajus/global-agent#29]
Can you provide documentation on how to use `global-agent` with a proxy, programmatically?

I used to do this with `global-tunnel-ng` : 
```js
globalTunnel.initialize({
  host: 'it29.nordvpn.com',
  port: 80,
  proxyAuth: 'username:password, // optional authentication
  sockets: 50, // optional pool size for each http and https
  protocol: 'http:'
})

```

how to provide hostname, port and authentication?

thanks

**Comment by roccomuso** [comment]
I ended up using something like: 

> process.env.GLOBAL_AGENT_HTTPS_PROXY=`http://${username}:${password}@${host}`

The problem is I keep getting this now:

> (node:2364226) UnhandledPromiseRejectionWarning: UnexpectedStateError: Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be "http:".


Isn't https supposed to work?

**Comment by gajus** [comment]
`process.env.GLOBAL_AGENT_HTTPS_PROXY` is the way to go.

The other question is covered in other GitHub issues.
