### ISSUE TITLE
axios request timeout not working with global-agent

### ISSUE THREAD

**Issue by puneetkumar712** [gajus/global-agent#33]
axios request timeout not working with global-agent.
Request doesn't timeout

**Comment by gajus** [comment]
Please contribute a PR demonstrating the behaviour.

**Comment by puneetkumar712** [comment]
Behaviour Timeout is not working as per below code snippet.
Axios timeout didn't worked.

require('global-agent/bootstrap');
const Axios = require("axios");

exports.handler = async (event) => {
  const client = Axios.create({ timeout: 5000});
  console.log("Request started");
  const res = await client.get("https://sampleapi.com/api/timeoutcheck" );   
//Any api taking more then 5 seconds and request didn't timed out as timeout provided in axios
  console.log("Response", res.data, res.status);
  const response = {
    statusCode: 200,
    body: JSON.stringify("Hello from Lambda!"),
  };
  return response;
};
