### ISSUE TITLE
Support separate HTTPS proxy configuration

### ISSUE THREAD

**Issue by rarkins** [gajus/global-agent#5]
Instead of having a single env variable for http and https, it would be ideal to have the option of configuring a HTTPS proxy. It's pretty common in enterprise to support HTTP_PROXY, HTTPS_PROXY, NO_PROXY so essentially we're just following that convention in case someone has a different proxy for HTTP and HTTPS.

As background, we'd like to use this package in Renovate Bot, there is a discussion here: https://github.com/renovatebot/renovate/issues/3547

**Comment by fgreinacher** [comment]
@gajus Would you take a PR for this? I'd add support for `GLOBAL_AGENT_HTTPS_PROXY` to https://github.com/gajus/global-agent/blob/master/src/routines/bootstrap.js and if set pass it on to https://github.com/gajus/global-agent/blob/master/src/classes/HttpsProxyAgent.js
